jaffle_shop:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: tpidai.postgres.database.azure.com
      port: 5432
      user: tpidaiadmin
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: postgres
      schema: dbt_test

    prod:
      type: postgres
      threads: 1
      host: tpidai.postgres.database.azure.com
      port: 5432
      user: tpidaiadmin
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: postgres
      schema: dbt_test

  target: dev